CREATE TABLE FAVORITOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    NOME_DISCO VARCHAR(200) NOT NULL,
    ARTISTA VARCHAR(200),
    ANO VARCHAR(10),
    CAPA_URL VARCHAR(500),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);
