DROP DATABASE IF EXISTS MeuSistemaDB;
CREATE DATABASE MeuSistemaDB;
USE MeuSistemaDB;

CREATE TABLE IF NOT EXISTS EMPRESA (
    ID_EMPRESA INT NOT NULL AUTO_INCREMENT COMMENT 'Chave
    Primária da Empresa',
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(255),
    CNPJ VARCHAR(18) UNIQUE,
    TELEFONE VARCHAR(20),
    PRIMARY KEY (ID_EMPRESA)
    );
    
    CREATE TABLE IF NOT EXISTS VINIL_EXPRESS (
    ID_VINIL_EXPRESS INT NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária de Vínculo Expresso',
    LOGIN_ACESSO VARCHAR(50) NOT NULL UNIQUE,
    DESC_ACESSO VARCHAR(100),
    SENHA_ACESSO VARCHAR(255) NOT NULL,
    ID_EMPRESA INT NOT NULL,
    PRIMARY KEY (ID_VINIL_EXPRESS),
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);

CREATE TABLE IF NOT EXISTS DISCOS (
    ID_DISCOSISTEMA INT NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária do Conteúdo',
    DT_PUBLICACAO DATE,
    TEXTO_MSG TEXT,
    ID_CATEGORIA INT,
    ANO_LANCAMENTO INT,
    PRECO_DS DECIMAL(10, 2),
    ID_VINIL_EXPRESS INT NOT NULL,
    PRIMARY KEY (ID_DISCOSISTEMA),
    FOREIGN KEY (ID_VINIL_EXPRESS) REFERENCES VINIL_EXPRESS(ID_VINIL_EXPRESS)
);

CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária do Usuário',
    NOME_COMPLETO VARCHAR(150) NOT NULL,
    LOGIN_ACESSO VARCHAR(50) UNIQUE NOT NULL,
    CPF VARCHAR(14) UNIQUE,
    E_MAIL VARCHAR(100) UNIQUE,
    DT_NASCIMENTO DATE,
    SENHA_SISTEMA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS DUVIDAS (
    ID_DUVIDAS INT NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Dúvida',
    NOME_DUVIDA VARCHAR(100),
    CORPO_DUVIDA TEXT,
    ASSUNTO VARCHAR(100) NOT NULL,
    STATUS VARCHAR(20),
    MENSAGEM TEXT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_DUVIDAS),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS POSSUI (
    ID_DISCOSISTEMA INT NOT NULL COMMENT 'FK para DISCOS',
    ID_USUARIO INT NOT NULL COMMENT 'FK para USUARIO',
    PRIMARY KEY (ID_DISCOSISTEMA, ID_USUARIO),
    FOREIGN KEY (ID_DISCOSISTEMA) REFERENCES DISCOS(ID_DISCOSISTEMA),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
