USE vinilexpress;

CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_COMPLETO VARCHAR(150) NOT NULL,
    LOGIN_ACESSO VARCHAR(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    E_MAIL VARCHAR(120) NOT NULL,
    DT_NASCIMENTO DATE,
    SENHA_SISTEMA VARCHAR(100) NOT NULL
);
